### ISSUE TITLE
Questions about loss functions

### ISSUE THREAD

**Issue by WWork1** [HyunWookL/TILDE-Q#1]
May I ask what format of input should the TILDE-Q loss function accept? Assuming my input is (B, T), where B is the batch size and T represents the sequence length.

**Comment by HyunWookL** [comment]
Thank you for your question! 
TILDE-Q supports any number of channels (i.e., univariate or multivariate time-series) with shape (B, T, C)
To utilize TILDE-Q, you simply change your input from (B, T) to (B, T, 1).

**Comment by WWork1** [comment]
Thank you for your answer.
